packages:
  - 'screeps-connectivity'
  - 'screeps-client'
  - 'screeps-mod-client'
  - 'xxscreeps-mod-client'
  - 'screeps-desktop'
  - 'screeps-client-proxy'
autoInstallPeers: false
allowBuilds:
  '@xxscreeps/pathfinder': true
  esbuild: true
  isolated-vm: true
  ivm-inspect: true
overrides:
  undici: '^7.28.0'
  js-yaml@3: 3.15.0
  js-yaml@4: '^4.3.0'
  esbuild: '^0.28.1'
